version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: utp_web_dev_db
    environment:
      POSTGRES_DB: utp_web_dev
      POSTGRES_USER: utp_user
      POSTGRES_PASSWORD: utp_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "listen_addresses=*"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utp_user -d utp_web_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local 